background_opacity 0.7

# Seamless SSH clipboard experience
clipboard_control write-clipboard write-primary read-clipboard read-primary

# kitty-kitten-search
map kitty_mod+f      launch --allow-remote-control kitty +kitten kitty_search/search.py @active-kitty-window-id
